MODEL:
  VID:
    ENABLE: True
    METHOD: "cvc_stft"#zheli yingai xie base erfei  cvc-stft-ruguo shi zhe ge de hua ,jiu xuyao gai CVCVIDSTFTDataset
    #from .cvcvid_stft import CVCVIDSTFTDataset
    STFT:
      MIN_OFFSET: -9
      MAX_OFFSET: 9
      TRAIN_REF_NUM: 2
      TEST_REF_NUM: 10
  META_ARCHITECTURE: "GeneralizedRCNNSTFT"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  RPN_ONLY: True
  FCOS_ON: True
  STFT_ON: True
  BACKBONE:
    CONV_BODY: "R-50-FPN-RETINANET"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
    STAGE_WITH_DCN: (False, True, True, True)
    WITH_MODULATED_DCN: False
    DEFORMABLE_GROUPS: 1
    STAGE_WITH_GCB: (False, True, True, True)
  RETINANET:
    USE_C5: False
  FCOS:
    NUM_CLASSES: 2
    FPN_STRIDES: [8, 16, 32, 64, 128]
    INFERENCE_TH: 0.05
    NMS_TH: 0.6
    PRE_NMS_TOP_N: 1000
    NORM_REG_TARGETS: True
    CENTERNESS_ON_REG: True
    CENTER_SAMPLING_RADIUS: 1.5
    IOU_LOSS_TYPE: "giou"
  STFT:
    OFFSET_WEIGHT_STD: 0.01
    IOU_THRESH: 0.1
    BBOX_STD: [0.5, 0.5, 0.5, 0.5]
    REG_BETA: 0.11
DATASETS:
  TRAIN: ("Kvasir-SEG_train_videos",)
  TEST: ("Kvasir-SEG_val_videos",)

INPUT:
  MIN_SIZE_TRAIN: (480,)
  MAX_SIZE_TRAIN: 608
  MIN_SIZE_TEST: 480
  MAX_SIZE_TEST: 608
DATALOADER:
  SIZE_DIVISIBILITY: 32
  NUM_WORKERS: 4 #这个不变
SOLVER:
  BASE_LR: 0.001 #加大了学习率
  WEIGHT_DECAY: 0.0001
  IMS_PER_BATCH: 1 #调小了
  WARMUP_METHOD: "linear"
  WARMUP_ITERS: 100 #全线调小
  CHECKPOINT_PERIOD: 50
  TEST_PERIOD: 50
  MAX_ITER: 1000
  LR_TYPE: "step"
  GAMMA: 0.5
  STEPS: (500, 750, 850)
TEST:
  IMS_PER_BATCH: 1
  DETECTIONS_PER_IMG: 300


